name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3
  NODE_VERSION: 23

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [env.NODE_VERSION]
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Lint
        run: pnpm lint

  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [env.NODE_VERSION]

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Format
        run: pnpm format

  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [env.NODE_VERSION]

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Typecheck
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [env.NODE_VERSION]
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Test
        run: pnpm test

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [env.NODE_VERSION]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/setup
      - name: Install Playwright Browsers
        run: pnpm test:e2e:install
      - name: Run Playwright tests
        run: pnpm test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
